"""Expanded curated catalog of incentive programs.

These supplement :mod:`._curated` with a broader set of programs documented
in DSIRE Florida, the IRA's per-technology rebate caps, additional Florida
statutes and Department of Revenue exemptions, additional utility offerings,
and additional Tampa Bay county / city housing programs.

Each record is sourced from a publicly-cited URL.  Records keep
``confidence_score`` honest -- entries that may have changed since
2026-05-04 receive a lower score so the review queue picks them up.
"""

from __future__ import annotations

from typing import List

from ..schema import AmountType, Level, RawIncentive, RawType, today_iso
from ._curated import _default_ongoing


def _today() -> str:
    return today_iso()


# ---------------------------------------------------------------------------
# Federal IRA technology-specific rebates (Sections 50121 / 50122)
# ---------------------------------------------------------------------------


def federal_extras() -> List[RawIncentive]:
    today = _today()
    return _default_ongoing([
        RawIncentive(
            program_name="IRA Heat Pump Space Heating / Cooling Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=8000,
            amount_text="Up to $8,000 per home for income-qualified households installing a qualifying electric heat pump.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["heat_pump"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description=(
                "Per-technology cap inside HEEHRA: up to $8,000 toward the cost of a qualifying "
                "electric heat pump for space heating and cooling."
            ),
            eligibility_notes=(
                "Households at or below 80% AMI can receive up to 100% of project cost; "
                "80%-150% AMI up to 50%; above 150% AMI ineligible. Implemented through state "
                "energy offices."
            ),
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="IRA Heat Pump Water Heater Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=1750,
            amount_text="Up to $1,750 toward a qualifying electric heat pump water heater.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["heat_pump_water_heater"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description="HEEHRA per-technology cap for heat pump water heaters.",
            eligibility_notes="Income tier rules and state-administered rollout same as HEEHRA umbrella.",
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.83,
        ),
        RawIncentive(
            program_name="IRA Electric Stove / Cooktop / Oven Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=840,
            amount_text="Up to $840 toward a qualifying electric / induction cooking appliance.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["induction_stove"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description="HEEHRA cap for induction / electric cooking appliances replacing gas units.",
            eligibility_notes="Subject to state implementation timeline and income tier scaling.",
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.82,
        ),
        RawIncentive(
            program_name="IRA Heat Pump Clothes Dryer Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=840,
            amount_text="Up to $840 toward a qualifying ENERGY STAR heat pump clothes dryer.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["heat_pump_dryer"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description="HEEHRA cap for heat pump clothes dryers replacing electric resistance / gas dryers.",
            eligibility_notes="Income tier scaling identical to HEEHRA umbrella.",
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.82,
        ),
        RawIncentive(
            program_name="IRA Electrical Panel Upgrade Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=4000,
            amount_text="Up to $4,000 toward a qualifying electrical service panel upgrade.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["electrical_panel_upgrade"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description="HEEHRA cap for upgrading the electrical service panel to enable electrification.",
            eligibility_notes="Subject to HEEHRA income tier rules and state rollout.",
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.82,
        ),
        RawIncentive(
            program_name="IRA Wiring Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=2500,
            amount_text="Up to $2,500 for non-panel wiring upgrades supporting electrification.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["wiring"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description="HEEHRA per-technology cap for branch / circuit wiring upgrades.",
            eligibility_notes="HEEHRA income tier rules apply.",
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.82,
        ),
        RawIncentive(
            program_name="IRA Insulation, Air Sealing, and Ventilation Rebate (HEEHRA)",
            level=Level.federal,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=1600,
            amount_text="Up to $1,600 toward insulation, air sealing, and ventilation improvements.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["insulation", "air_sealing", "ventilation"],
            income_required=True,
            income_limit_pct_ami=150,
            requires_homeownership=False,
            description="HEEHRA cap for envelope improvements supporting electrified mechanical systems.",
            eligibility_notes="HEEHRA income tier rules apply.",
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/home-energy-rebates",
            source_url="https://www.energy.gov/scep/home-energy-rebates",
            expires_at="2031-09-30",
            last_verified_at=today,
            confidence_score=0.83,
        ),
        RawIncentive(
            program_name="Federal EV Charger Tax Credit (Section 30C, Alt Fuel Refueling Property)",
            level=Level.federal,
            type=RawType.tax_credit,
            amount_type=AmountType.percentage,
            amount_value=30,
            amount_max=1000,
            amount_text="30% of cost of EV charging equipment, up to $1,000 for residential installations in eligible census tracts.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["ev_charger"],
            requires_homeownership=True,
            income_required=False,
            description=(
                "Federal income tax credit for installing residential EV charging equipment in "
                "low-income or non-urban census tracts."
            ),
            eligibility_notes=(
                "Property must be located in a designated low-income community or non-urban census "
                "tract. Claimed on IRS Form 8911."
            ),
            program_administrator="Internal Revenue Service",
            application_url="https://www.irs.gov/credits-deductions/alternative-fuel-vehicle-refueling-property-credit",
            source_url="https://www.irs.gov/credits-deductions/alternative-fuel-vehicle-refueling-property-credit",
            expires_at="2032-12-31",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="Federal Clean Vehicle Tax Credit (Section 30D)",
            level=Level.federal,
            type=RawType.tax_credit,
            amount_type=AmountType.up_to,
            amount_value=7500,
            amount_text="Up to $7,500 for qualifying new clean vehicles meeting battery and assembly requirements.",
            eligible_property_types=["all"],
            eligible_project_types=["ev_purchase"],
            requires_homeownership=False,
            income_required=True,
            description=(
                "Tax credit for qualifying new plug-in electric and fuel-cell vehicles, structured "
                "as $3,750 for critical minerals + $3,750 for battery components requirements."
            ),
            eligibility_notes=(
                "Income limits: $300K joint, $225K head of household, $150K single. MSRP cap $80K "
                "for SUVs/trucks/vans, $55K for cars. Vehicle must be assembled in North America."
            ),
            program_administrator="Internal Revenue Service",
            application_url="https://www.irs.gov/credits-deductions/credits-for-new-clean-vehicles-purchased-in-2023-or-after",
            source_url="https://www.irs.gov/credits-deductions/credits-for-new-clean-vehicles-purchased-in-2023-or-after",
            expires_at="2032-12-31",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="Federal Used Clean Vehicle Tax Credit (Section 25E)",
            level=Level.federal,
            type=RawType.tax_credit,
            amount_type=AmountType.up_to,
            amount_value=4000,
            amount_text="Up to $4,000 (or 30% of sale price, whichever is less) for qualifying used clean vehicles.",
            eligible_property_types=["all"],
            eligible_project_types=["ev_purchase"],
            requires_homeownership=False,
            income_required=True,
            description="Tax credit for qualifying used EVs / plug-in hybrids purchased from a dealer.",
            eligibility_notes=(
                "Income limits: $150K joint, $112,500 head of household, $75K single. Sale price <= "
                "$25,000. Vehicle must be at least 2 model years old. Buyer cannot have claimed "
                "the credit in prior 3 years."
            ),
            program_administrator="Internal Revenue Service",
            application_url="https://www.irs.gov/credits-deductions/used-clean-vehicle-credit",
            source_url="https://www.irs.gov/credits-deductions/used-clean-vehicle-credit",
            expires_at="2032-12-31",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="DOE Weatherization Assistance Program (Federal WAP)",
            level=Level.federal,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=8500,
            amount_text="Free weatherization services averaging ~$8,000 per home for income-qualified households.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=[
                "weatherization", "insulation", "air_sealing", "duct_sealing", "hvac",
            ],
            requires_homeownership=False,
            income_required=True,
            description=(
                "Federal Weatherization Assistance Program funded by DOE and delivered through "
                "state and local sub-grantees. Provides home energy upgrades at no cost to the "
                "household."
            ),
            eligibility_notes=(
                "Households at or below 200% of federal poverty level, automatically eligible if "
                "receiving SSI or TANF. In Florida administered by the Department of Commerce and "
                "delivered locally (Hillsborough County is a sub-grantee)."
            ),
            program_administrator="U.S. Department of Energy / Florida Department of Commerce",
            application_url="https://www.energy.gov/scep/wap/weatherization-assistance-program",
            source_url="https://www.energy.gov/scep/wap/weatherization-assistance-program",
            last_verified_at=today,
            confidence_score=0.88,
        ),
        RawIncentive(
            program_name="LIHEAP (Low Income Home Energy Assistance Program)",
            level=Level.federal,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=2000,
            amount_text="Bill-payment and crisis assistance up to ~$2,000 per household per year (varies by Florida sub-grantee).",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["bill_payment", "energy_crisis"],
            requires_homeownership=False,
            income_required=True,
            description=(
                "Federally-funded household energy assistance for income-qualified households, "
                "including bill payment, crisis benefits, and limited weatherization."
            ),
            eligibility_notes=(
                "Households at or below 60% of state median income or 150% of federal poverty "
                "guidelines (Florida threshold). Apply through your local community action agency."
            ),
            program_administrator="U.S. Department of Health and Human Services / Florida Department of Commerce",
            application_url="https://www.acf.hhs.gov/ocs/programs/liheap",
            source_url="https://www.acf.hhs.gov/ocs/programs/liheap",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="USDA Section 504 Home Repair Loan and Grant",
            level=Level.federal,
            type=RawType.loan,
            amount_type=AmountType.up_to,
            amount_value=40000,
            amount_text="1% loan up to $40,000 (or grant up to $10,000 for elderly very-low-income owners) for repairs and modernization.",
            eligible_property_types=["sfh"],
            eligible_project_types=["rehab", "accessibility", "code_repair", "weatherization"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=50,
            description=(
                "USDA Rural Development program for very-low-income rural homeowners to repair, "
                "improve, or modernize their homes, or remove health and safety hazards."
            ),
            eligibility_notes=(
                "Property must be in an eligible USDA-designated rural area (parts of Hillsborough "
                "County qualify). Applicant must be 62+ to receive the grant component. Maximum "
                "grant + loan combined: $50,000."
            ),
            program_administrator="USDA Rural Development",
            application_url="https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-repair-loans-grants/fl",
            source_url="https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-repair-loans-grants/fl",
            last_verified_at=today,
            confidence_score=0.82,
        ),
        RawIncentive(
            program_name="HUD Section 203(k) Rehabilitation Mortgage Insurance",
            level=Level.federal,
            type=RawType.financing,
            amount_type=AmountType.up_to,
            amount_value=750000,
            amount_text="FHA-insured mortgage that bundles purchase + rehabilitation costs into one loan.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["rehab", "purchase_plus_rehab"],
            requires_homeownership=True,
            income_required=False,
            description=(
                "FHA-insured loan product allowing borrowers to finance both purchase (or refi) and "
                "rehabilitation of a residential property in a single mortgage."
            ),
            eligibility_notes=(
                "Property must be a 1-4 unit primary residence. Loan limit follows local FHA limit "
                "(approximately $498,000-$524,000 for Hillsborough County in 2026). Limited 203(k) "
                "covers projects up to $35,000."
            ),
            program_administrator="U.S. Department of Housing and Urban Development",
            application_url="https://www.hud.gov/program_offices/housing/sfh/203k",
            source_url="https://www.hud.gov/program_offices/housing/sfh/203k",
            last_verified_at=today,
            confidence_score=0.86,
        ),
        RawIncentive(
            program_name="VA Energy Efficient Mortgage (EEM)",
            level=Level.federal,
            type=RawType.financing,
            amount_type=AmountType.up_to,
            amount_value=6000,
            amount_text="Up to $6,000 of qualifying energy-efficiency improvements added to a VA loan.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["energy_efficiency", "weatherization", "windows", "hvac"],
            requires_homeownership=True,
            income_required=False,
            description=(
                "VA-guaranteed loan add-on that allows eligible veterans to roll energy-efficiency "
                "improvement costs into a VA purchase or refinance loan."
            ),
            eligibility_notes=(
                "Borrower must be eligible for VA loan benefits. Improvements must be cost-"
                "effective per VA energy audit. Available on VA purchase, refinance, and IRRRL "
                "loans."
            ),
            program_administrator="U.S. Department of Veterans Affairs",
            application_url="https://www.benefits.va.gov/HOMELOANS/purchaseco_eem.asp",
            source_url="https://www.benefits.va.gov/HOMELOANS/purchaseco_eem.asp",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="Federal Solar Investment Tax Credit (ITC) - Commercial",
            level=Level.federal,
            type=RawType.tax_credit,
            amount_type=AmountType.percentage,
            amount_value=30,
            amount_text="30% Investment Tax Credit (Section 48E) for commercial-scale solar with bonus credit adders for domestic content and energy communities.",
            eligible_property_types=["commercial", "multifamily"],
            eligible_project_types=["solar_pv", "battery_storage", "wind", "geothermal"],
            requires_homeownership=False,
            income_required=False,
            description=(
                "Federal investment tax credit for commercial-scale solar, storage, and other "
                "qualifying clean-energy property. Bonus 10% adders available for domestic content "
                "and energy-community placement; up to 20% additional for low-income communities."
            ),
            eligibility_notes=(
                "Available to businesses, non-profits (via direct pay), and tax-exempt organizations. "
                "Owners of multifamily housing can apply. Includes prevailing-wage / apprenticeship "
                "requirements above 1 MW."
            ),
            program_administrator="Internal Revenue Service",
            application_url="https://www.irs.gov/credits-deductions/businesses/clean-electricity-investment-credit",
            source_url="https://www.irs.gov/credits-deductions/businesses/clean-electricity-investment-credit",
            expires_at="2034-12-31",
            last_verified_at=today,
            confidence_score=0.84,
        ),
    ])


# ---------------------------------------------------------------------------
# Florida-specific extras
# ---------------------------------------------------------------------------


def state_extras() -> List[RawIncentive]:
    today = _today()
    return _default_ongoing([
        RawIncentive(
            program_name="Florida Solar and CHP Sales Tax Exemption (Statute 212.08(7)(ccc))",
            level=Level.state,
            type=RawType.exemption,
            amount_type=AmountType.percentage,
            amount_value=100,
            amount_text="Sales and use tax fully waived on solar energy systems and components, including combined heat-and-power systems.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily", "commercial"],
            eligible_project_types=["solar_pv", "solar_water_heating", "chp"],
            requires_homeownership=False,
            income_required=False,
            description="Statewide sales tax exemption for solar energy and CHP equipment.",
            eligibility_notes="Equipment must be FSEC-certified.",
            program_administrator="Florida Department of Revenue",
            application_url="https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx",
            source_url="https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx",
            last_verified_at=today,
            confidence_score=0.86,
        ),
        RawIncentive(
            program_name="Florida Net Metering for Customer-Owned Renewable Generation",
            level=Level.state,
            type=RawType.subsidy,
            amount_type=AmountType.percentage,
            amount_value=100,
            amount_text="Excess generation credited at retail rate (transitioning to lower rates after 2026 per Florida PSC rule changes).",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily", "commercial"],
            eligible_project_types=["solar_pv", "wind", "battery_storage"],
            requires_homeownership=True,
            income_required=False,
            utility_provider="All Florida investor-owned utilities",
            description=(
                "Florida Public Service Commission rule requiring all IOUs (TECO, Duke, FPL, "
                "Gulf Power) to interconnect customer-owned renewable systems and credit excess "
                "generation."
            ),
            eligibility_notes=(
                "System size up to 2 MW. Tier 1 (<=10 kW) has streamlined interconnection. "
                "Net-metering compensation rate is being phased down after 2026; current "
                "customers grandfathered."
            ),
            program_administrator="Florida Public Service Commission",
            application_url="https://www.psc.state.fl.us/",
            source_url="https://www.psc.state.fl.us/",
            last_verified_at=today,
            confidence_score=0.78,
        ),
        RawIncentive(
            program_name="Florida Resilient SRF (Wastewater / Stormwater Resilience Loans)",
            level=Level.state,
            type=RawType.investment,
            amount_type=AmountType.up_to,
            amount_value=10000000,
            amount_text="Low-interest loans for resilient water and wastewater infrastructure (eligible borrowers are local governments).",
            eligible_property_types=["all"],
            eligible_project_types=["water_resilience", "stormwater"],
            requires_homeownership=False,
            income_required=False,
            description="Florida Department of Environmental Protection State Revolving Fund loans for resilient water infrastructure.",
            eligibility_notes="Eligible applicants are units of local government. Indirect benefit to property owners through utility-rate moderation.",
            program_administrator="Florida Department of Environmental Protection",
            application_url="https://floridadep.gov/wra/srf",
            source_url="https://floridadep.gov/wra/srf",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Florida Resilient Florida Grant Program",
            level=Level.state,
            type=RawType.investment,
            amount_type=AmountType.up_to,
            amount_value=5000000,
            amount_text="Grants to local governments for sea-level-rise / flooding resilience projects.",
            eligible_property_types=["all"],
            eligible_project_types=["flood_mitigation", "stormwater", "shoreline_protection"],
            requires_homeownership=False,
            income_required=False,
            description=(
                "Statewide grants for resilience planning and capital projects coordinated by the "
                "Florida Office of Resilience and Coastal Protection."
            ),
            eligibility_notes="Eligible applicants are counties and municipalities.",
            program_administrator="Florida Department of Environmental Protection",
            application_url="https://floridadep.gov/ResilientFlorida",
            source_url="https://floridadep.gov/ResilientFlorida",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Florida HOME Investment Partnerships Program",
            level=Level.state,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=60000,
            amount_text="HUD-funded HOME dollars passed through to local governments and non-profits for housing development, rehab, and DPA.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["down_payment", "rehab", "new_construction"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            description="HOME formula funds passed through Florida Housing Finance Corporation to local participating jurisdictions.",
            eligibility_notes="Households at or below 80% AMI. Specific use varies by jurisdiction.",
            program_administrator="Florida Housing Finance Corporation",
            application_url="https://www.floridahousing.org/programs/special-programs",
            source_url="https://www.floridahousing.org/programs/special-programs",
            last_verified_at=today,
            confidence_score=0.78,
        ),
        RawIncentive(
            program_name="Florida CDBG-DR (Community Development Block Grant - Disaster Recovery)",
            level=Level.state,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=350000,
            amount_text="Disaster recovery funds for housing repair, replacement, and reconstruction in declared-disaster areas.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["disaster_recovery", "rehab", "reconstruction"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=120,
            description=(
                "Federally-funded long-term recovery program administered by the Florida Department "
                "of Commerce. Includes the Hurricane Ian / Nicole and Hurricane Idalia recovery "
                "rounds active in 2026."
            ),
            eligibility_notes=(
                "Property must be in a presidentially-declared disaster area. Households up to 120% "
                "AMI eligible, with prioritization for those <=80% AMI. Application through Florida "
                "Department of Commerce."
            ),
            program_administrator="Florida Department of Commerce",
            application_url="https://floridajobs.org/community-planning-and-development/assistance-for-government-and-nonprofit-organizations/community-development-block-grant-disaster-recovery-program",
            source_url="https://floridajobs.org/",
            last_verified_at=today,
            confidence_score=0.74,
        ),
        RawIncentive(
            program_name="Florida Home-Buyer Loan Program (HFA First Mortgage Bond Loans)",
            level=Level.state,
            type=RawType.financing,
            amount_type=AmountType.up_to,
            amount_value=750000,
            amount_text="Below-market 30-year fixed-rate first mortgage funded by tax-exempt mortgage revenue bonds.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["home_purchase"],
            requires_homeownership=True,
            income_required=True,
            description="Bond-funded first mortgage program offered through participating lenders.",
            eligibility_notes=(
                "Income and acquisition-cost limits set per county. Borrower must complete a "
                "Florida-Housing-approved homebuyer education course."
            ),
            program_administrator="Florida Housing Finance Corporation",
            application_url="https://www.floridahousing.org/programs/homebuyer-overview-page",
            source_url="https://www.floridahousing.org/programs/homebuyer-overview-page",
            last_verified_at=today,
            confidence_score=0.78,
        ),
        RawIncentive(
            program_name="Florida Salute Our Soldiers (SOS) Military Loan Program",
            level=Level.state,
            type=RawType.financing,
            amount_type=AmountType.up_to,
            amount_value=10000,
            amount_text="Discounted-rate first mortgage with up to $10,000 down-payment assistance for active-duty service members and veterans.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["home_purchase", "down_payment"],
            requires_homeownership=True,
            income_required=True,
            description="Florida Housing program tailored to active-duty military, reservists, and veterans.",
            eligibility_notes=(
                "Borrower must qualify for VA, FHA, USDA, or conventional financing. Income / "
                "acquisition limits apply. Available statewide."
            ),
            program_administrator="Florida Housing Finance Corporation",
            application_url="https://www.floridahousing.org/programs/homebuyer-overview-page/salute-our-soldiers",
            source_url="https://www.floridahousing.org/programs/homebuyer-overview-page/salute-our-soldiers",
            last_verified_at=today,
            confidence_score=0.78,
        ),
        RawIncentive(
            program_name="Florida HEMR / Hurricane Loss Mitigation Program (HLMP)",
            level=Level.state,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=10000,
            amount_text="Subsidized mitigation upgrades for income-qualified Florida homeowners (mobile homes, hurricane research and outreach).",
            eligible_property_types=["sfh", "manufactured", "multifamily"],
            eligible_project_types=["wind_mitigation", "tie_downs", "roof_strengthening"],
            requires_homeownership=True,
            income_required=True,
            description=(
                "State-funded program operated by Florida Division of Emergency Management to "
                "harden mobile / manufactured homes, retrofit single-family homes, and fund "
                "hurricane-research outreach."
            ),
            eligibility_notes=(
                "Specific funding sub-programs vary year-to-year. Mobile home tie-down assistance "
                "available statewide for income-qualified owners."
            ),
            program_administrator="Florida Division of Emergency Management",
            application_url="https://www.floridadisaster.org/dem/mitigation/",
            source_url="https://www.floridadisaster.org/dem/mitigation/",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Florida Veterans Affairs Property Tax Exemption (Statute 196.081 / 196.082)",
            level=Level.state,
            type=RawType.exemption,
            amount_type=AmountType.percentage,
            amount_value=100,
            amount_text="Total exemption from property tax for veterans rated 100% permanent and totally disabled (or surviving spouse).",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["property_tax_relief"],
            requires_homeownership=True,
            income_required=False,
            description="Constitutional and statutory total property-tax exemption for qualifying disabled veterans.",
            eligibility_notes=(
                "Veteran must be Florida resident, honorably discharged, and 100% permanently and "
                "totally disabled (combat-related). Surviving spouse can carry over the exemption "
                "subject to conditions."
            ),
            program_administrator="Florida Department of Revenue / County Property Appraisers",
            application_url="https://floridarevenue.com/property/Pages/Taxpayers_Exemptions.aspx",
            source_url="https://floridarevenue.com/property/Pages/Taxpayers_Exemptions.aspx",
            last_verified_at=today,
            confidence_score=0.85,
        ),
        RawIncentive(
            program_name="Florida Senior / Low-Income Property Tax Exemption (Statute 196.075)",
            level=Level.state,
            type=RawType.exemption,
            amount_type=AmountType.up_to,
            amount_value=50000,
            amount_text="Additional homestead exemption up to $50,000 for low-income seniors 65+.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["property_tax_relief"],
            requires_homeownership=True,
            income_required=True,
            description="Local-option additional homestead exemption for low-income seniors. Hillsborough County and the City of Tampa both offer it.",
            eligibility_notes=(
                "Must be 65+ as of January 1, have legal/equitable title to the homestead, and "
                "household adjusted gross income below the annually-adjusted threshold (~$36,614 "
                "for 2026)."
            ),
            program_administrator="County Property Appraisers (Hillsborough)",
            application_url="https://www.hcpafl.org/Property-Info/Exemptions",
            source_url="https://www.hcpafl.org/Property-Info/Exemptions",
            last_verified_at=today,
            confidence_score=0.84,
        ),
        RawIncentive(
            program_name="Florida Homestead Exemption (Statute 196.031)",
            level=Level.state,
            type=RawType.exemption,
            amount_type=AmountType.up_to,
            amount_value=50000,
            amount_text="Up to $50,000 homestead exemption from assessed property value (with Save Our Homes 3% cap on annual assessment increases).",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["property_tax_relief"],
            requires_homeownership=True,
            income_required=False,
            description="Florida's foundational homestead exemption, providing up to $50,000 off assessed value plus the Save Our Homes annual assessment cap.",
            eligibility_notes=(
                "Must own and reside in the property as primary residence as of January 1. File "
                "with the Hillsborough County Property Appraiser before March 1."
            ),
            program_administrator="Hillsborough County Property Appraiser",
            application_url="https://www.hcpafl.org/Property-Info/Exemptions",
            source_url="https://www.hcpafl.org/Property-Info/Exemptions",
            last_verified_at=today,
            confidence_score=0.92,
        ),
        RawIncentive(
            program_name="Florida Save Our Homes Portability",
            level=Level.state,
            type=RawType.exemption,
            amount_type=AmountType.up_to,
            amount_value=500000,
            amount_text="Transfer up to $500,000 of accumulated Save Our Homes assessment differential to a new Florida homestead within 3 years.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["property_tax_relief"],
            requires_homeownership=True,
            income_required=False,
            description="Allows existing Florida homeowners to carry their Save Our Homes assessment cap to a new primary residence.",
            eligibility_notes=(
                "Must establish new homestead within 3 tax years of abandoning the previous one. "
                "Apply with Form DR-501T at the new county's property appraiser."
            ),
            program_administrator="Hillsborough County Property Appraiser",
            application_url="https://www.hcpafl.org/Property-Info/Exemptions",
            source_url="https://www.hcpafl.org/Property-Info/Exemptions",
            last_verified_at=today,
            confidence_score=0.88,
        ),
        RawIncentive(
            program_name="Florida Renewable Energy Production Tax Credit (Statute 220.193) - Commercial",
            level=Level.state,
            type=RawType.tax_credit,
            amount_type=AmountType.per_unit,
            amount_value=0.01,
            amount_text="$0.01 per kWh production tax credit for qualifying renewable-energy facilities.",
            eligible_property_types=["commercial"],
            eligible_project_types=["solar_pv", "wind", "biomass", "hydrogen"],
            requires_homeownership=False,
            income_required=False,
            description="Corporate income tax credit on qualifying renewable energy generation in Florida. Periodically funded; subject to annual cap.",
            eligibility_notes="Available to corporations operating qualifying generation facilities in Florida. Subject to annual statutory cap.",
            program_administrator="Florida Department of Revenue",
            application_url="https://floridarevenue.com/",
            source_url="https://floridarevenue.com/",
            last_verified_at=today,
            confidence_score=0.65,
        ),
    ])


# ---------------------------------------------------------------------------
# Utility extras (TECO, Duke, neighboring utilities)
# ---------------------------------------------------------------------------


def utility_extras() -> List[RawIncentive]:
    today = _today()
    return _default_ongoing([
        RawIncentive(
            program_name="TECO ENERGY STAR Smart Thermostat Rebate",
            level=Level.utility,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=50,
            amount_text="$50 rebate for installing a qualifying ENERGY STAR-certified smart thermostat.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["smart_thermostat"],
            requires_homeownership=False,
            income_required=False,
            utility_provider="Tampa Electric (TECO)",
            description="Bill-credit rebate for adopting smart-thermostat control of HVAC.",
            eligibility_notes="Customer must enroll in TECO's Energy Planner or related demand-response program.",
            program_administrator="Tampa Electric",
            application_url="https://www.tampaelectric.com/residential/saveenergy/energystarsmartthermostat/",
            source_url="https://www.tampaelectric.com/residential/saveenergy/energystarsmartthermostat/",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="TECO Prime Time Plus Demand Response",
            level=Level.utility,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=84,
            amount_text="Bill credit up to ~$84/year for allowing TECO to briefly cycle the central AC during peak events.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["demand_response"],
            requires_homeownership=False,
            income_required=False,
            utility_provider="Tampa Electric (TECO)",
            description="TECO demand-response program for residential central AC customers.",
            eligibility_notes="Requires installation of a TECO-supplied switch on the AC condenser.",
            program_administrator="Tampa Electric",
            application_url="https://www.tampaelectric.com/residential/saveenergy/primetimeplus/",
            source_url="https://www.tampaelectric.com/residential/saveenergy/primetimeplus/",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="TECO Neighborhood Weatherization Program",
            level=Level.utility,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=2500,
            amount_text="Free home weatherization upgrades (insulation, duct repair, weather-stripping) for income-qualified TECO customers.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["weatherization", "insulation", "duct_sealing"],
            requires_homeownership=False,
            income_required=True,
            utility_provider="Tampa Electric (TECO)",
            description="No-cost weatherization program for income-qualified TECO residential customers.",
            eligibility_notes="Income-eligibility threshold set by TECO program guidelines (generally <=200% of federal poverty level).",
            program_administrator="Tampa Electric",
            application_url="https://www.tampaelectric.com/residential/saveenergy/neighborhoodweatherization/",
            source_url="https://www.tampaelectric.com/residential/saveenergy/neighborhoodweatherization/",
            last_verified_at=today,
            confidence_score=0.78,
        ),
        RawIncentive(
            program_name="TECO Energy Star New Construction Incentive",
            level=Level.utility,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=750,
            amount_text="Builder incentive up to $750 per ENERGY STAR-certified new home built in TECO territory.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["new_construction"],
            requires_homeownership=True,
            income_required=False,
            utility_provider="Tampa Electric (TECO)",
            description="Per-home incentive for builders constructing ENERGY STAR-certified homes in TECO service territory.",
            eligibility_notes="Builder must enroll in TECO's ENERGY STAR program and meet HERS Index thresholds.",
            program_administrator="Tampa Electric",
            application_url="https://www.tampaelectric.com/residential/saveenergy/energystarnewconstruction/",
            source_url="https://www.tampaelectric.com/residential/saveenergy/energystarnewconstruction/",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Peoples Gas High-Efficiency Natural Gas Equipment Rebate",
            level=Level.utility,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=475,
            amount_text="Rebates up to $475 on qualifying high-efficiency gas appliances (water heaters, dryers, furnaces, ranges).",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["natural_gas_appliance"],
            requires_homeownership=True,
            income_required=False,
            utility_provider="Peoples Gas",
            description="Rebates for installing qualifying high-efficiency natural-gas equipment.",
            eligibility_notes="Residential Peoples Gas customers; equipment must be installed by a licensed contractor.",
            program_administrator="Peoples Gas (TECO Energy)",
            application_url="https://www.peoplesgas.com/residential/save-energy-and-money/",
            source_url="https://www.peoplesgas.com/residential/save-energy-and-money/",
            last_verified_at=today,
            confidence_score=0.66,
        ),
        RawIncentive(
            program_name="Duke Energy Florida Smart $aver Window AC / Smart Thermostat",
            level=Level.utility,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=125,
            amount_text="Up to $125 rebate / bill credit for enrolling a smart thermostat or qualifying AC.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["smart_thermostat"],
            requires_homeownership=False,
            income_required=False,
            utility_provider="Duke Energy Florida",
            description="Combination instant rebate + bill credit for smart thermostat enrollment in Duke Energy Florida residential service.",
            eligibility_notes="Customer must remain enrolled in Duke's demand-response program.",
            program_administrator="Duke Energy Florida",
            application_url="https://www.duke-energy.com/home/products/smart-thermostat",
            source_url="https://www.duke-energy.com/home/products/smart-thermostat",
            last_verified_at=today,
            confidence_score=0.66,
        ),
        RawIncentive(
            program_name="Duke Energy Florida Neighborhood Energy Saver",
            level=Level.utility,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=600,
            amount_text="Free energy-efficiency direct-install (LED bulbs, smart strips, weatherization) for income-qualified neighborhoods.",
            eligible_property_types=["sfh", "condo", "townhouse", "multifamily"],
            eligible_project_types=["weatherization", "lighting"],
            requires_homeownership=False,
            income_required=True,
            utility_provider="Duke Energy Florida",
            description="Direct-install program targeted to limited-income neighborhoods served by Duke Energy Florida.",
            eligibility_notes="Eligibility determined by census-tract income data; customers in eligible areas are contacted directly.",
            program_administrator="Duke Energy Florida",
            application_url="https://www.duke-energy.com/home/products/neighborhood-energy-saver",
            source_url="https://www.duke-energy.com/home/products/neighborhood-energy-saver",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Duke Energy Florida EV Charger Rebate",
            level=Level.utility,
            type=RawType.rebate,
            amount_type=AmountType.up_to,
            amount_value=1133,
            amount_text="Rebate covering installation of a Duke-managed Level-2 EV charger plus monthly bill discounts for off-peak charging.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["ev_charger"],
            requires_homeownership=True,
            income_required=False,
            utility_provider="Duke Energy Florida",
            description="Park & Plug residential EV charger program with installation rebate and time-of-use bill discount.",
            eligibility_notes="Customer must enroll in Duke's residential EV time-of-use rate.",
            program_administrator="Duke Energy Florida",
            application_url="https://www.duke-energy.com/home/products/electric-vehicles/charger-prep-credit",
            source_url="https://www.duke-energy.com/home/products/electric-vehicles/charger-prep-credit",
            last_verified_at=today,
            confidence_score=0.6,
        ),
    ])


# ---------------------------------------------------------------------------
# Local extras (Tampa, Hillsborough, neighboring counties)
# ---------------------------------------------------------------------------


def local_extras() -> List[RawIncentive]:
    today = _today()
    return _default_ongoing([
        RawIncentive(
            program_name="Hillsborough County CDBG Owner-Occupied Rehabilitation",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=60000,
            amount_text="Up to $60,000 rehabilitation assistance funded by CDBG for income-qualified Hillsborough homeowners.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["rehab", "code_repair", "accessibility"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            county="Hillsborough",
            description="HUD CDBG-funded rehabilitation program operated alongside SHIP rehab; covers code-related repairs, roofs, HVAC, and accessibility.",
            eligibility_notes="<=80% AMI. Cannot be used in combination with SHIP rehab on the same project; staff selects best fit.",
            program_administrator="Hillsborough County Affordable Housing Services",
            application_url="https://hcfl.gov/services/housing/own-a-home/home-repairs",
            source_url="https://hcfl.gov/services/housing/own-a-home/home-repairs",
            last_verified_at=today,
            confidence_score=0.74,
        ),
        RawIncentive(
            program_name="Hillsborough County Mobile Home Replacement Program",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=120000,
            amount_text="Up to $120,000 to replace a substandard mobile home with a new ENERGY STAR manufactured home for income-qualified owners.",
            eligible_property_types=["manufactured"],
            eligible_project_types=["replacement", "manufactured_home"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            county="Hillsborough",
            description="Hillsborough SHIP-funded program to replace severely deteriorated mobile homes occupied by income-qualified owners.",
            eligibility_notes="Owner must own land or have long-term lease. Replacement units must meet HUD energy standards.",
            program_administrator="Hillsborough County Affordable Housing Services",
            application_url="https://hcfl.gov/services/housing/own-a-home/home-repairs",
            source_url="https://hcfl.gov/services/housing/own-a-home/home-repairs",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Hillsborough County Emergency Repair Program",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=15000,
            amount_text="Up to $15,000 in emergency repairs (roof leaks, sewer / septic, HVAC failure) for income-qualified Hillsborough homeowners.",
            eligible_property_types=["sfh", "condo", "townhouse", "manufactured"],
            eligible_project_types=["roof", "septic", "hvac", "emergency_repair"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            county="Hillsborough",
            description="SHIP-funded emergency repair grants for life-safety / habitability issues.",
            eligibility_notes="<=80% AMI; documentation of imminent health/safety hazard required.",
            program_administrator="Hillsborough County Affordable Housing Services",
            application_url="https://hcfl.gov/services/housing/own-a-home/home-repairs",
            source_url="https://hcfl.gov/services/housing/own-a-home/home-repairs",
            last_verified_at=today,
            confidence_score=0.74,
        ),
        RawIncentive(
            program_name="Hillsborough County Disaster Recovery Repair Assistance",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=120000,
            amount_text="Repair / reconstruction assistance for storm-damaged homes funded through CDBG-DR.",
            eligible_property_types=["sfh", "condo", "townhouse", "manufactured"],
            eligible_project_types=["disaster_recovery", "rehab", "reconstruction"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=120,
            county="Hillsborough",
            description="Long-term recovery program for hurricane-damaged homes in Hillsborough County administered with state CDBG-DR funds.",
            eligibility_notes="Property must have documented unmet need from a presidentially-declared storm. Income tiers prioritize <=80% AMI.",
            program_administrator="Hillsborough County Affordable Housing Services / Florida Department of Commerce",
            application_url="https://hcfl.gov/services/housing/disaster-recovery",
            source_url="https://hcfl.gov/services/housing/disaster-recovery",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="City of Tampa Emergency Repair Program",
            level=Level.city,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=20000,
            amount_text="Up to $20,000 in emergency / code-related repairs for income-qualified Tampa homeowners.",
            eligible_property_types=["sfh", "townhouse"],
            eligible_project_types=["roof", "septic", "hvac", "emergency_repair"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            city="Tampa",
            description="City of Tampa SHIP/CDBG-funded program addressing imminent code or safety failures.",
            eligibility_notes="Primary residence inside Tampa city limits; <=80% AMI.",
            program_administrator="City of Tampa Housing & Community Development",
            application_url="https://www.tampa.gov/housing-and-community-development/programs/owner-occupied-rehabilitation",
            source_url="https://www.tampa.gov/housing-and-community-development/programs/owner-occupied-rehabilitation",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="City of Tampa Roof Replacement Program",
            level=Level.city,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=18000,
            amount_text="Roof-replacement grant up to $18,000 for income-qualified Tampa homeowners.",
            eligible_property_types=["sfh", "townhouse"],
            eligible_project_types=["roof"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            city="Tampa",
            description="Targeted roof-replacement grant tied to City of Tampa's owner-occupied rehab pipeline.",
            eligibility_notes="Primary residence in Tampa city limits; <=80% AMI; documented roof failure.",
            program_administrator="City of Tampa Housing & Community Development",
            application_url="https://www.tampa.gov/housing-and-community-development/programs/owner-occupied-rehabilitation",
            source_url="https://www.tampa.gov/housing-and-community-development/programs/owner-occupied-rehabilitation",
            last_verified_at=today,
            confidence_score=0.66,
        ),
        RawIncentive(
            program_name="City of Tampa Mobility Modification Program",
            level=Level.city,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=10000,
            amount_text="Accessibility modifications (ramps, grab bars, walk-in showers) up to $10,000 for income-qualified residents with disabilities.",
            eligible_property_types=["sfh", "townhouse", "condo"],
            eligible_project_types=["accessibility"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            city="Tampa",
            description="Targeted accessibility modifications for elderly or disabled Tampa residents to age in place.",
            eligibility_notes="Primary residence in Tampa city limits; <=80% AMI; documented disability or elderly status.",
            program_administrator="City of Tampa Housing & Community Development",
            application_url="https://www.tampa.gov/housing-and-community-development",
            source_url="https://www.tampa.gov/housing-and-community-development",
            last_verified_at=today,
            confidence_score=0.6,
        ),
        RawIncentive(
            program_name="City of Tampa Lead-Based Paint Hazard Reduction",
            level=Level.city,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=25000,
            amount_text="Lead-paint hazard reduction grant for older homes (built before 1978) in Tampa city limits.",
            eligible_property_types=["sfh", "townhouse"],
            eligible_project_types=["lead_paint_remediation"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            city="Tampa",
            description="HUD-funded program reducing lead-paint hazards for income-qualified Tampa families with children under 6.",
            eligibility_notes="Property built before 1978; child under 6 or pregnant resident; <=80% AMI.",
            program_administrator="City of Tampa Housing & Community Development",
            application_url="https://www.tampa.gov/housing-and-community-development",
            source_url="https://www.tampa.gov/housing-and-community-development",
            last_verified_at=today,
            confidence_score=0.62,
        ),
        RawIncentive(
            program_name="Pinellas County Down Payment Assistance Program",
            level=Level.county,
            type=RawType.loan,
            amount_type=AmountType.up_to,
            amount_value=40000,
            amount_text="Up to $40,000 in deferred 0% second-mortgage assistance for income-qualified first-time homebuyers in Pinellas County.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["down_payment", "closing_costs"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=120,
            county="Pinellas",
            description="Pinellas County Community Development Department-administered down-payment assistance for first-time homebuyers across the Tampa Bay MSA.",
            eligibility_notes="<=120% AMI; first-time homebuyer; required homebuyer education; assistance is a 0% deferred second mortgage.",
            program_administrator="Pinellas County Community Development",
            application_url="https://pinellas.gov/buy-rent-improve-home/",
            source_url="https://pinellas.gov/buy-rent-improve-home/",
            last_verified_at=today,
            confidence_score=0.74,
        ),
        RawIncentive(
            program_name="Pinellas County Owner-Occupied Rehabilitation",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=70000,
            amount_text="Forgivable rehabilitation loan up to $70,000 for income-qualified Pinellas County owners.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["rehab", "code_repair", "roof", "hvac"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            county="Pinellas",
            description="Pinellas County Community Development rehab program for owner-occupied homes with code-related needs.",
            eligibility_notes="<=80% AMI; primary residence in Pinellas County (excluding cities running their own SHIP).",
            program_administrator="Pinellas County Community Development",
            application_url="https://pinellas.gov/buy-rent-improve-home/",
            source_url="https://pinellas.gov/buy-rent-improve-home/",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="City of St. Petersburg Down Payment Assistance",
            level=Level.city,
            type=RawType.loan,
            amount_type=AmountType.up_to,
            amount_value=40000,
            amount_text="Up to $40,000 deferred-payment second mortgage for first-time homebuyers in St. Petersburg.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["down_payment", "closing_costs"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=120,
            city="St. Petersburg",
            description="City of St. Petersburg first-time homebuyer assistance program funded through SHIP and CDBG.",
            eligibility_notes="<=120% AMI; first-time homebuyer; primary residence within St. Petersburg city limits.",
            program_administrator="City of St. Petersburg Housing & Community Development",
            application_url="https://www.stpete.org/residents/housing___neighborhoods/index.php",
            source_url="https://www.stpete.org/residents/housing___neighborhoods/index.php",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Pasco County Down Payment Assistance Program",
            level=Level.county,
            type=RawType.loan,
            amount_type=AmountType.up_to,
            amount_value=40000,
            amount_text="Up to $40,000 down-payment / closing-cost assistance for income-qualified Pasco buyers.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["down_payment", "closing_costs"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=120,
            county="Pasco",
            description="Pasco County Community Development first-time homebuyer assistance program (SHIP).",
            eligibility_notes="<=120% AMI; first-time homebuyer; primary residence in Pasco County.",
            program_administrator="Pasco County Community Development",
            application_url="https://www.pascocountyfl.net/176/Community-Development",
            source_url="https://www.pascocountyfl.net/176/Community-Development",
            last_verified_at=today,
            confidence_score=0.7,
        ),
        RawIncentive(
            program_name="Manatee County Down Payment Assistance Program",
            level=Level.county,
            type=RawType.loan,
            amount_type=AmountType.up_to,
            amount_value=40000,
            amount_text="SHIP-funded down-payment / closing-cost assistance for income-qualified Manatee County buyers.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["down_payment", "closing_costs"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=120,
            county="Manatee",
            description="Manatee County Neighborhood Services SHIP program for first-time homebuyers.",
            eligibility_notes="<=120% AMI; first-time homebuyer; primary residence in Manatee County.",
            program_administrator="Manatee County Neighborhood Services",
            application_url="https://www.mymanatee.org/departments/neighborhood_services",
            source_url="https://www.mymanatee.org/departments/neighborhood_services",
            last_verified_at=today,
            confidence_score=0.65,
        ),
        RawIncentive(
            program_name="Pasco County Owner-Occupied Rehabilitation Program",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=60000,
            amount_text="Up to $60,000 in rehabilitation funding for income-qualified Pasco County homeowners.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["rehab", "code_repair", "roof", "hvac"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            county="Pasco",
            description="Pasco County SHIP-funded rehab program addressing code-related repairs.",
            eligibility_notes="<=80% AMI; primary residence in Pasco County.",
            program_administrator="Pasco County Community Development",
            application_url="https://www.pascocountyfl.net/176/Community-Development",
            source_url="https://www.pascocountyfl.net/176/Community-Development",
            last_verified_at=today,
            confidence_score=0.66,
        ),
        RawIncentive(
            program_name="Tampa Bay Habitat for Humanity Critical Home Repair",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=10000,
            amount_text="Free / discounted critical home repair services for income-qualified Tampa Bay homeowners.",
            eligible_property_types=["sfh", "condo", "townhouse"],
            eligible_project_types=["roof", "rehab", "accessibility"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=80,
            county="Hillsborough",
            description=(
                "Habitat for Humanity-coordinated critical home repair program serving Hillsborough "
                "and surrounding counties."
            ),
            eligibility_notes="<=80% AMI; primary residence in Habitat's service area.",
            program_administrator="Habitat for Humanity of Hillsborough County",
            application_url="https://www.habitathillsborough.org/repairs/",
            source_url="https://www.habitathillsborough.org/repairs/",
            last_verified_at=today,
            confidence_score=0.6,
        ),
        RawIncentive(
            program_name="Rebuilding Together Tampa Bay Home Repair",
            level=Level.county,
            type=RawType.grant,
            amount_type=AmountType.up_to,
            amount_value=10000,
            amount_text="Volunteer-supplied home repair and accessibility improvements for elderly, disabled, and veteran homeowners.",
            eligible_property_types=["sfh", "townhouse"],
            eligible_project_types=["accessibility", "roof", "weatherization"],
            requires_homeownership=True,
            income_required=True,
            income_limit_pct_ami=60,
            county="Hillsborough",
            description=(
                "Volunteer-driven home repair non-profit serving low-income elderly, disabled, and "
                "veteran homeowners across Tampa Bay."
            ),
            eligibility_notes="<=60% AMI; primary residence; demonstrated need.",
            program_administrator="Rebuilding Together Tampa Bay",
            application_url="https://www.rebuildingtogethertb.org/",
            source_url="https://www.rebuildingtogethertb.org/",
            last_verified_at=today,
            confidence_score=0.55,
        ),
    ])
